
[[Hello!]]
`af`Hallo
`ar`مرحبً
`bg`Здравей
`ca`Hola
`cs`Ahoj
`cy`Helo
`da`Hej
`de`Grüß Gott
`el`Γειά σας
`eo`Saluton
`es`¡Hola
`et`Tere päevast
`eu`Kaixo
`fa`سلام
`fi`Hyvää päivää
`fj`Bula
`fo`Hey
`fr`Salut
`ga`Haigh
`ha`Sannu
`hi`नमस्त
`hr`Bok
`hu`Szia
`id`Hai
`is`Halló
`it`Ciao
`ja`今日は
`jv`Selamat sore
`ka`გამარჯობა
`kk`Сәлем
`ko`안녕하십니까
`la`Ave
`lo`ຂໍໃຫ້ໂຊກດີ
`lt`Sveikas
`mt`Saħħa
`nl`Hoi
`no`Hei
`pl`Cześć
`pt`Olá
`ro`Bună
`ru`Здравствуйте
`sa`नमस्कार
`sk`Ahoj
`sl`Pozdravljeni
`sq`Tungjatjeta
`sr`Здраво
`sv`Hallå
`sw`Jambo
`tr`Merhaba
`uk`Привіт
`vi`Chào bạn
`zh`你好
`zu`Sawubona

[[Statistics]]
`ja`スタティスティックス
`de`Statistiken
`it`Statistiche

[[Messages]]
`ja`メッセージ

[[Quit]]
`ja`終了

[[Update Load Order]]
`ja`更新 Load Order
`de`Aktualisieren Load Order
`it`Aggiorna Load Order

[[Close]]
`ja`閉じる

[[Select All]]
`ja`すべてのテキストを選択する
`de`Wähle alle
`it`Seleziona tutti

[[Paste]]
`ja`ペーストする

[[Open File]]
`ja`ファイルを開く

[[Debug]]
`ja`デバッグ機能

[[%s - Debug Output]]
`ja`%s - デバッグ出力

[[(Not Found)]]
`ja`(見当たらない)
`de`(Nicht Gefunden)
`it`(Non Trovata)

[[Input Plugin List from File]]

[[Current Load Order]]

[[(Right click in this pane for options)]]

[[Proposed Load Order Sorted by mlox]]

